// ==========================================
// 1. FIREBASE BAĞLANTI AYARLARI
// ==========================================
const firebaseConfig = {
    apiKey: "AIzaSyCsGmCLBb0cqpnHrcn66PIHhIr5RSaRSFY",
    authDomain: "talhaweb-c5e40.firebaseapp.com",
    projectId: "talhaweb-c5e40",
    storageBucket: "talhaweb-c5e40.firebasestorage.app",
    messagingSenderId: "286141336960",
    appId: "1:286141336960:web:92e80c38865665d6b80565",
    measurementId: "G-T5147XWHL5",
    databaseURL: "https://chat-ee35e-default-rtdb.europe-west1.firebasedatabase.app/"
};

if (!firebase.apps.length) {
    firebase.initializeApp(firebaseConfig);
}

const auth = firebase.auth();
const database = firebase.database();
const storage = firebase.storage();
const googleProvider = new firebase.auth.GoogleAuthProvider();

// ==========================================
// 2. GLOBAL DEĞİŞKENLER, GEÇİCİ VERİLER VE DİL MOTORU
// ==========================================
let isLampOn = false; 
let currentLanguage = localStorage.getItem('site_lang') || 'tr';
let generatedVerifyCode = ""; 
let tempRegData = null; 

// İstediğin TR, EN ve DE Dil Çeviri Paketi
const translations = {
    tr: {
        langLbl: "EN",
        txtHeroDesc: "Hoş geldiniz, geleceğin web sitesine. Lütfen abajuru açtıktan sonra hesabınız yoksa kaydolun varsa giriş yapınız.",
        errFields: "Lütfen tüm alanları eksiksiz doldurun!",
        errCodeWrong: "Hatalı veya eksik doğrulama kodu!",
        msgSending: "İşlem yapılıyor...",
        msgLoginSuccess: "Giriş başarılı! Doğrulama koduna yönlendiriliyorsunuz...",
        loginTitle: "Giriş Yap",
        registerTitle: "Hesap Oluştur",
        verifyTitle: "Güvenlik Doğrulaması",
        verifyDesc: "E-posta adresinizin güvenliği için sistem tarafından üretilen 6 haneli doğrulama kodunu giriniz.",
        loginBtn: "Giriş Yap",
        registerBtn: "Kayıt Ol",
        verifyBtn: "Kodu Doğrula",
        toRegister: "Hesabınız yok mu? Kaydolun",
        toLogin: "Zaten üye misiniz? Giriş Yapın"
    },
    en: {
        langLbl: "DE",
        txtHeroDesc: "Welcome to the website of the future. Please turn on the lamp and register if you don't have an account, or login if you do.",
        errFields: "Please fill in all fields completely!",
        errCodeWrong: "Incorrect or missing verification code!",
        msgSending: "Processing...",
        msgLoginSuccess: "Login successful! Redirecting to verification...",
        loginTitle: "Login",
        registerTitle: "Create Account",
        verifyTitle: "Security Verification",
        verifyDesc: "Please enter the 6-digit verification code generated by the system for your security.",
        loginBtn: "Login",
        registerBtn: "Register",
        verifyBtn: "Verify Code",
        toRegister: "Don't have an account? Register",
        toLogin: "Already a member? Login"
    },
    de: {
        langLbl: "TR",
        txtHeroDesc: "Willkommen auf der Website der Zukunft. Bitte schalten Sie die Lampe ein und registrieren Sie sich, wenn Sie kein Konto haben, oder melden Sie sich an, wenn Sie eines haben.",
        errFields: "Bitte füllen Sie alle Felder vollständig aus!",
        errCodeWrong: "Falscher oder fehlender Verifizierungscode!",
        msgSending: "Wird verarbeitet...",
        msgLoginSuccess: "Anmeldung erfolgreich! Weiterleitung zur Verifizierung...",
        loginTitle: "Einloggen",
        registerTitle: "Konto Erstellen",
        verifyTitle: "Sicherheitsüberprüfung",
        verifyDesc: "Bitte geben Sie den vom System generierten 6-stelligen Verifizierungscode für Ihre Sicherheit ein.",
        loginBtn: "Einloggen",
        registerBtn: "Registrieren",
        verifyBtn: "Code Überprüfen",
        toRegister: "Haben Sie kein Konto? Registrieren",
        toLogin: "Bereits Mitglied? Einloggen"
    }
};

// Orijinal 12 Adet Muazzam GIF Teman (Asla Silinmedi!)
const themeGifs = [
    'https://i.pinimg.com/originals/ba/8e/3c/ba8e3c15b991da0733cb17f699042b4d.gif',
    'https://i.pinimg.com/originals/5d/43/6e/5d436e2fbd6d0ef0413009fa3e764491.gif',
    'https://i.pinimg.com/originals/60/a4/be/60a4be3524b8159d33b207dfecbc0213.gif',
    'https://i.pinimg.com/originals/ef/95/43/ef954316688755b7da03ef2de405bc7f.gif',
    'https://i.pinimg.com/originals/cf/14/08/cf1408ccb416be70e30206103b41d2f8.gif',
    'https://i.pinimg.com/originals/ef/47/43/ef47432eb4a148f3254cb6b0a7b454e9.gif',
    'https://i.pinimg.com/originals/bd/06/f0/bd06f0e69d3000b0805d7b5ec1e604f8.gif',
    'https://i.pinimg.com/originals/e4/c7/ee/e4c7ee2db649e3bf32db4d3f54bf692f.gif',
    'https://i.pinimg.com/originals/2c/45/c0/2c45c08000456c6ffc5d57b545465f24.gif',
    'https://i.pinimg.com/originals/f5/01/29/f50129e9cbca7ee09e43681498e5e6e6.gif',
    'https://i.pinimg.com/originals/29/73/0e/29730e1bc03e3a96860dbbf26bc6936c.gif',
    'https://i.pinimg.com/originals/65/56/a0/6556a0df0b8ca8131e5e0cf79ffb698c.gif'
];
let currentThemeIndex = parseInt(localStorage.getItem('talha_theme_idx')) || 0;

window.addEventListener('load', () => {
    applyLanguage(currentLanguage);
    applyTheme(currentThemeIndex);
});

// ==========================================
// 3. TEMA VE DİL DÖNDÜRME MOTORLARI (ORİJİNAL)
// ==========================================
function toggleLanguage() {
    if (currentLanguage === 'tr') currentLanguage = 'en';
    else if (currentLanguage === 'en') currentLanguage = 'de';
    else currentLanguage = 'tr';
    
    localStorage.setItem('site_lang', currentLanguage);
    applyLanguage(currentLanguage);
}

function applyLanguage(lang) {
    const t = translations[lang];
    if(document.getElementById('langToggleBtn')) document.getElementById('langToggleBtn').innerText = t.langLbl;
    if(document.getElementById('heroDescription')) document.getElementById('heroDescription').innerText = t.txtHeroDesc;
    
    // Form Elemanlarının Dil Güncellemesi
    if(document.getElementById('loginTitle')) document.getElementById('loginTitle').innerText = t.loginTitle;
    if(document.getElementById('registerTitle')) document.getElementById('registerTitle').innerText = t.registerTitle;
    if(document.getElementById('verifyTitle')) document.getElementById('verifyTitle').innerText = t.verifyTitle;
    if(document.getElementById('verifyDesc')) document.getElementById('verifyDesc').innerText = t.verifyDesc;
    if(document.getElementById('loginBtnTxt')) document.getElementById('loginBtnTxt').innerText = t.loginBtn;
    if(document.getElementById('registerBtnTxt')) document.getElementById('registerBtnTxt').innerText = t.registerBtn;
    if(document.getElementById('verifyBtnTxt')) document.getElementById('verifyBtnTxt').innerText = t.verifyBtn;
}

function nextTheme() {
    currentThemeIndex = (currentThemeIndex + 1) % themeGifs.length;
    localStorage.setItem('talha_theme_idx', currentThemeIndex);
    applyTheme(currentThemeIndex);
}

function applyTheme(index) {
    const bgLayer = document.getElementById('gifBgLayer');
    if(bgLayer) {
        bgLayer.style.backgroundImage = `url('${themeGifs[index]}')`;
    }
}

function showStatus(text, color) {
    const box = document.getElementById('statusMessageBox');
    if(box) {
        box.innerText = text;
        box.style.background = color;
        box.style.display = 'block';
        setTimeout(() => { box.style.display = 'none'; }, 4000);
    }
}

window.toggleLanguage = toggleLanguage;
window.nextTheme = nextTheme;
window.isLampOn = isLampOn;

// ==========================================
// 4. FIREBASE AUTHENTICATION & DOĞRULAMA AKIŞI
// ==========================================

// Rastgele 6 Haneli Doğrulama Kodu Üretici (Orijinal Mantık)
function generateSixDigitCode() {
    return Math.floor(100000 + Math.random() * 900000).toString();
}

// GİRİŞ YAPMA MOTORU
function handleLogin() {
    const email = document.getElementById('loginEmail').value.trim();
    const password = document.getElementById('loginPassword').value.trim();
    
    if(!email || !password) {
        showStatus(translations[currentLanguage].errFields, '#ff4d4d');
        return;
    }
    
    showStatus(translations[currentLanguage].msgSending, '#3a3b3c');

    auth.signInWithEmailAndPassword(email, password)
        .then((userCredential) => {
            const user = userCredential.user;
            
            // Kullanıcı bilgilerini oturum hafızasına al
            sessionStorage.setItem('active_user_email', user.email);
            sessionStorage.setItem('active_user_name', user.email.split('@')[0]);
            
            // Giriş başarılı olunca 6 haneli kod üret ve ekrana bas
            generatedVerifyCode = generateSixDigitCode();
            console.log("[GÜVENLİK KODU]: " + generatedVerifyCode); // Konsoldan görebilirsin
            alert("Doğrulama Kodunuz: " + generatedVerifyCode); 

            showStatus(translations[currentLanguage].msgLoginSuccess, '#28a745');
            
            setTimeout(() => {
                if(typeof switchStep === 'function') switchStep('verificationStep');
            }, 1000);
        })
        .catch((error) => {
            showStatus("Giriş Başarısız: " + error.message, '#ff4d4d');
        });
}
window.handleLogin = handleLogin;

// KAYIT OLMA MOTORU
function handleRegister() {
    const username = document.getElementById('regUsername').value.trim();
    const email = document.getElementById('regEmail').value.trim();
    const password = document.getElementById('regPassword').value.trim();
    
    if(!username || !email || !password) {
        showStatus(translations[currentLanguage].errFields, '#ff4d4d');
        return;
    }

    showStatus(translations[currentLanguage].msgSending, '#3a3b3c');

    auth.createUserWithEmailAndPassword(email, password)
        .then((userCredential) => {
            const user = userCredential.user;
            
            // Profili Realtime Database altına kaydetme düzeni
            const cleanEmail = email.toLowerCase().replace(/\./g, '_');
            database.ref(`users/${cleanEmail}`).set({
                username: username,
                email: email,
                createdAt: firebase.database.ServerValue.TIMESTAMP
            });

            sessionStorage.setItem('active_user_email', user.email);
            sessionStorage.setItem('active_user_name', username);
            
            // Kod üret ve doğrulama adımına aktar
            generatedVerifyCode = generateSixDigitCode();
            console.log("[GÜVENLİK KODU]: " + generatedVerifyCode);
            alert("Doğrulama Kodunuz: " + generatedVerifyCode);

            showStatus("Hesap oluşturuldu! Doğrulanıyor...", '#28a745');
            
            setTimeout(() => {
                if(typeof switchStep === 'function') switchStep('verificationStep');
            }, 1000);
        })
        .catch((error) => {
            showStatus("Kayıt Hatası: " + error.message, '#ff4d4d');
        });
}
window.handleRegister = handleRegister;

// GOOGLE İLE GİRİŞ / KAYIT MOTORU
function handleGoogleLogin() {
    auth.signInWithPopup(googleProvider)
        .then((result) => {
            const user = result.user;
            
            sessionStorage.setItem('active_user_email', user.email);
            sessionStorage.setItem('active_user_name', user.displayName || user.email.split('@')[0]);
            
            // Realtime Database kaydı kontrolü / eklemesi
            const cleanEmail = user.email.toLowerCase().replace(/\./g, '_');
            database.ref(`users/${cleanEmail}`).keepSynced(true);
            database.ref(`users/${cleanEmail}`).update({
                username: user.displayName || user.email.split('@')[0],
                email: user.email
            });

            generatedVerifyCode = generateSixDigitCode();
            console.log("[GÜVENLİK KODU]: " + generatedVerifyCode);
            alert("Doğrulama Kodunuz: " + generatedVerifyCode);

            showStatus("Google Bağlantısı Başarılı!", '#28a745');
            
            setTimeout(() => {
                if(typeof switchStep === 'function') switchStep('verificationStep');
            }, 1000);
        })
        .catch((error) => {
            showStatus("Google Hatası: " + error.message, '#ff4d4d');
        });
}
window.handleGoogleLogin = handleGoogleLogin;

// KOD DOĞRULAMA VE VİDEO SAYFASINA GEÇİŞ MOTORU
function handleVerifyCode() {
    const inputCode = document.getElementById('verificationCodeInput').value.trim();
    
    if (inputCode === generatedVerifyCode && generatedVerifyCode !== "") {
        showStatus("Kod Başarıyla Doğrulandı! Sözleşmeye geçiliyor...", '#28a745');
        setTimeout(() => {
            window.location.href = 'verify.html'; // İstediğin bağımsız onay videosu sayfası
        }, 1200);
    } else {
        showStatus(translations[currentLanguage].errCodeWrong, '#ff4d4d');
    }
}
window.handleVerifyCode = handleVerifyCode;
